# Generated by Django 5.1.7 on 2025-03-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='created_by',
            new_name='user',
        ),
    ]
